USE_CAMERA_STUB := true

# screen data
TARGET_SCREEN_WIDTH := 540
TARGET_SCREEN_HEIGHT := 960
DEVICE_RESOLUTION := 540x960
TARGET_RECOVERY_PIXEL_FORMAT := RGBX_8888

# TWRP configuration
# RECOVERY_VARIANT := twrp
RECOVERY_GRAPHICS_USE_LINELENGTH := true
ENABLE_LOKI_RECOVERY := true

# device data
TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := msm8960
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := krait
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_BOOTLOADER_BOARD_NAME := l1e

# kernel data
BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 androidboot.hardware=l1e user_debug=31 msm_rtb.filter=0x3F ehci-hcd.park=3 lpj=67724 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x80200000
BOARD_KERNEL_PAGESIZE := 2048
TARGET_KERNEL_SOURCE := kernel/lge/l1e
TARGET_KERNEL_CONFIG := l1e-perf_defconfig
TARGET_PREBUILT_KERNEL := device/lge/l1e/kernel

# partition sizes
BOARD_BOOTIMAGE_PARTITION_SIZE := 12582912
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 12582912
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1323302912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5475663872
BOARD_FLASH_BLOCK_SIZE := 131072

# force the ramdisk offset with the given argument
BOARD_MKBOOTIMG_ARGS := --ramdisk_offset 0x02000000

BOARD_HAS_NO_SELECT_BUTTON := true
